// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function migrationDatabaseUrl(): string | undefined {
  const explicitDirectUrl = process.env["DIRECT_URL"]?.trim();
  if (explicitDirectUrl) return explicitDirectUrl;

  const runtimeUrl = process.env["DATABASE_URL"]?.trim();
  if (!runtimeUrl) return undefined;

  try {
    const parsed = new URL(runtimeUrl);
    if (
      parsed.hostname.endsWith(".neon.tech") &&
      parsed.hostname.includes("-pooler.")
    ) {
      parsed.hostname = parsed.hostname.replace("-pooler.", ".");
      return parsed.toString();
    }
  } catch {
    // Prisma will report the original malformed URL with its normal error.
  }

  return runtimeUrl;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migration advisory locks are session-scoped and must bypass PgBouncer.
    // Runtime Prisma continues to use DATABASE_URL through the pg adapter.
    url: migrationDatabaseUrl(),
  },
});
