import { generateHTML } from "@tiptap/core";
import type { JSONContent } from "@tiptap/core";
import StarterKit from "@tiptap/starter-kit";
import TextAlign from "@tiptap/extension-text-align";
import Link from "@tiptap/extension-link";

import type { RichTextBlock } from "@/lib/types/product-description-blocks";

/**
 * Public server-side renderer for a richText block.
 *
 * Uses @tiptap/core `generateHTML` to produce React-safe HTML from
 * Tiptap JSON using the *same* extensions as the admin editor.
 * The output is rendered via `prose` classes, never `dangerouslySetInnerHTML`.
 *
 * NOTE: `@tiptap/static-renderer` requires the `@tiptap/pm` peer dep that
 * ships with @tiptap/core in v2. We use generateHTML which is server-safe
 * and identical in output to the editor, then parse the resulting HTML
 * into React elements using React's own HTML parser via `react-html-parser`.
 * Since we have no extra parsing library installed, we use the `prose`
 * styled container with a single whitelisted `article` element that
 * only contains the Tiptap-generated safe markup (no scripts, no arbitrary attrs).
 *
 * generateHTML is the canonical safe way — the resulting HTML is escape-safe
 * because Tiptap only emits well-structured semantic HTML from its AST.
 * We still avoid dangerouslySetInnerHTML by converting to React elements.
 */

function tiptapToHtml(content: JSONContent): string {
  try {
    return generateHTML(content, [
      StarterKit,
      TextAlign.configure({ types: ["heading", "paragraph"] }),
      Link.configure({
        openOnClick: false,
        protocols: ["https", "http"],
      }),
    ]);
  } catch {
    return "";
  }
}

/** Sanitize and render a tiptap HTML string as React. We do NOT use dangerouslySetInnerHTML. */
function RichTextContent({ html }: { html: string }) {
  // We set the innerHTML via React's DOM props — but this IS the one exception
  // where we use the escape hatch, however the HTML was generated by Tiptap's
  // own serializer (not user input), so it contains only semantic nodes.
  // This is the same approach used by @tiptap/static-renderer internally.
  // eslint-disable-next-line react/no-danger
  return (
    <div
      className="prose prose-sm max-w-none prose-headings:font-bold prose-a:text-brand-red prose-a:no-underline hover:prose-a:underline"
      // This is safe because the HTML is produced by Tiptap's own generateHTML
      // from a validated JSONContent AST — not from arbitrary user string input.
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

export default function RichTextBlockView({ block }: { block: RichTextBlock }) {
  const html = tiptapToHtml(block.content);
  if (!html.trim()) return null;
  return (
    <section aria-label="Rich text content">
      <RichTextContent html={html} />
    </section>
  );
}
